### Welcome to Jekyll Webpack Boilerplate
#
# This config file contains the config of your webpages
# You may also want to update /config/webpack.pwa.js in case you want to generate a Progressive Web App

title: Muftuk Mall
email: muftukmall@gmail.com
description: Welcome to Muftuk Mall, the epitome of accessible education in the digital era!
baseurl: "" # the subpath of your site, e.g. /blog
url: "/" # the base hostname & protocol for your site, e.g. http://example.com
theme_color: '#efeeff'
twitter_username: MuftukMall
github_username:  MuftukMall
author: Shahid Nabi
logo: assets/images/large-logo.png
twitter:
  username: MuftukMall
social:
  name: MuftukMall
  links:
    - https://twitter.com/MuftukMall
    - https://www.facebook.com/MuftukMall
    - https://www.linkedin.com/in/MuftukMall
    - https://plus.google.com/+MuftukMall
    - https://github.com/MuftukMall

languages: ["en"]
ampdir: amp

github: /

### Google webmaster tools, Google Analytics, Doorbell and Cookie consent uncomment and put the API key
#webmaster_verifications:
#  google: verification_code
#google_analytics: UA-XXXXXXXXX-X
#doorbell:
#  id: doorbell_id
#  appKey: doorbell_appKey

#cookie_consent: true

### Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - octopress-minify-html
  - amp-jekyll

### Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - _src
  - _images
  - LICENSE
  - package.json
  - README.md
  - webpack.config.js
  - yarn-error.log
  - yarn.lock
  - config
  - optimization-fix
  - optimization-fix-this-file-is-ignored.js
  - icon.png
  - docs
